name: Docs

on:
  push:
    branches: [main]
    paths:
      - 'docs/**'
      - package.json
      - README.md

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Setup Node JS
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: npm

      - name: Build Docs 📚
        run: |
          # un-ignore bundle.js
          mv docs/.gitignore .gitignore
          npm i
          npm build:docs
      - name: Deploy Pages 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: docs
